name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_ACTIONS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup Go Module Access Token
      run: |
        git config --global url."https://x-access-token:$GH_ACTIONS_TOKEN@github.com/fastcat/gdev".insteadOf https://github.com/fastcat/gdev

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '~1.25.0'

    - name: Setup Mage
      run: go tool mage -l

    - name: Check codegen
      run: |
        go generate -x ./...
        git diff --exit-code

    - name: Build
      run: go tool mage -v compile
    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v8.0.0
      # can use latest release nowadays
    - name: Other Lint
      run: go tool mage -v lint:other
    - name: Test
      run: go tool mage -v test
